mjesta = ['otok', 'zagreb', 'mostar', 'vinkovci',]
print("Original order")
print(mjesta)
print("Alphabetical order")
print(sorted(mjesta))
print("Original order")
print(mjesta)
print("Alphabetical reverse order")
print(sorted(mjesta, reverse=True))
print(mjesta)
mjesta.reverse()
print(mjesta)
mjesta.reverse()
print(mjesta)
mjesta.sort()
print(mjesta)
mjesta.sort(reverse=True)
print(mjesta)
